alias watch="watch -d"
alias diff="diff -u"
alias mv="mv -i"
alias less="less -ij4"
alias wttr="curl wttr.in"
alias livestreamer="livestreamer --http-header Client-ID=jzkbprff40iqj646a697cyrvl0zt2m6"
